//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobsForCoders.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employer
    {
        public Employer()
        {
            this.JobPostings = new HashSet<JobPosting>();
        }
    
        public int EmployerID { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string Cellphone { get; set; }
        public string Buzz_Words { get; set; }
        public string Operator { get; set; }
        public string Logo { get; set; }
        public string History { get; set; }
    
        public virtual ICollection<JobPosting> JobPostings { get; set; }
    }
}
