//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobsForCoders.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobSeeker
    {
        public int JobSeekerID { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public System.DateTime Birthdate { get; set; }
        public string Gender { get; set; }
        public string Education { get; set; }
        public string Objectives { get; set; }
        public string Introduction { get; set; }
        public string Links { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string Cellphone { get; set; }
        public string Buzz_Words { get; set; }
        public string Operator { get; set; }
    }
}
